lint:
  pipeline_todos: false
  template_strings: false
  pipeline_if_empty_null: false
  nf_test_content: false
  files_unchanged:
  - .github/PULL_REQUEST_TEMPLATE.md
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: "Zachary S.L. Foster, Martha Sudermann, Nicholas C. Cauldron, Fernanda I.
    Bocardo, Hung Phan, Jeﬀ H. Chang, Niklaus J. Grünwald"
  description: Surveillance of plant pathogens using high-throughput sequencing
  force: false
  is_nfcore: true
  name: pathogensurveillance
  org: nf-core
  outdir: .
  version: 1.1.0dev
