# Identification

```{r include=FALSE, eval=FALSE}
work_dir = "/media/fosterz/external_primary/files/projects/work/current/nf-core-plantpathsurveil/work/60/71f547293aa5d22f469ea3ee215581"
params = list(
  samp_data = "metadata_medium.csv",
  ref_data = "merged_assembly_stats.tsv",
  snp_phylos = list("xan_test_22_331_assembly.treefile"),
  ani_matrix = "comp.csv",
  core_phylo = "xan_test.treefile"
)
params = lapply(params, function(x) file.path(work_dir, x))
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 10, warning = FALSE)
```

```{r libraries}
library(phylocanvas)
library(ape)
```

```{r parse_inputs}
ref_meta <- read.csv(params$ref_data, sep = '\t')
ref_meta$modified_id <- gsub(ref_meta$LastMajorReleaseAccession, pattern = ".", replacement = "_", fixed = TRUE)
samp_meta <- read.csv(params$samp_data, sep = ',')
samp_meta$modified_id <- paste0(gsub(samp_meta$sample, pattern = "-", replacement = "_", fixed = TRUE), "_T1")
ani_matrix <-  read.csv(params$ani_matrix, sep = ',', check.names = FALSE)
core_tree <- ape::read.tree(params$core_phylo)
snp_trees <- ape::read.tree(params$snp_phylos)
```


## Core genome phylogeny


```{r core_phylo, fig.height = 7, eval = ! is.null(core_tree)}
# Identify which tips are samples and references
sample_ids <- core_tree$tip.label[core_tree$tip.label %in% samp_meta$modified_id]

# Root tree 
colnames(ani_matrix) <- gsub(colnames(ani_matrix), pattern = "[.-]", replacement = "_")
rownames(ani_matrix) <- colnames(ani_matrix)
group_ani <- ani_matrix[rownames(ani_matrix) %in% core_tree$tip.label, colnames(ani_matrix) %in% core_tree$tip.label]
core_tree <- root(core_tree, names(which.min(colMeans(group_ani[sample_ids, ]))))

# Set tip labels to taxon names for reference sequences
# TODO: need a more reliable way to get IDs
name_key <- c(
  ref_meta$Organism, 
  samp_meta$sample
)
names(name_key) <- c(
  ref_meta$modified_id,
  samp_meta$modified_id
)
core_tree$tip.label <- name_key[core_tree$tip.label]

# Plot tree
phycanv <- phylocanvas(core_tree, treetype = "rectangular", alignlabels = T, showscalebar = T, width = "100%")
phycanv
```

```{asis no_core_phylo, echo = is.null(core_tree)}
There is no tree to draw, probably because there were too few samples.
More info will be added later.
```



## SNP phylogeny


```{r snp_phylo, fig.height = 7, eval = ! is.null(snp_trees)}
# Root tree 
snp_trees <- root(snp_trees, "REF")

# Plot tree
phycanv <- phylocanvas(snp_trees, treetype = "rectangular", alignlabels = T, showscalebar = T, width = "100%")
phycanv
```

```{asis no_snp_phylo, echo = is.null(snp_trees)}
There is no tree to draw, probably because there were too few samples.
More info will be added later.
```
